import generators.electricity
import generators.gidro
import generators.kinematics
import generators.koleb
import generators.magnet
import generators.optics
import generators.quantum
import generators.sto
import generators.termo
import generators.value
import generators.variant
import generators.vishnyakova
import generators.waves
import generators.zsi_zse
