import generators.atomic
import generators.electricity
import generators.magnet
import generators.mechanics
import generators.optics
import generators.oscillation
import generators.personal
import generators.termodynamics
import generators.variant
