import generators.c_9_5_em_waves
import generators.electricity
import generators.magnet
import generators.mkt
import generators.optics
import generators.quantum
import generators.sto
import generators.termo
import generators.variant
import generators.vishnyakova
import generators.mechanics