import problems.cheshev
import problems.cloud
import problems.gendenshteyn10
import problems.gendenshteyn11
import problems.gendenshteyn7
import problems.gendenshteyn8
import problems.getaclass
import problems.savchenko
import problems.yakunin
