import library
import logging

log = logging.getLogger('task')

class Task(object):
    def __init__(self, text, answer=None, number=None):
        self.Text = text.strip('\n')
        self.Answer = answer
        self.Number = number

    def GetTex(self):
        text = library.formatter.formatText(self.Text, addIndent=4)
        result = None
        try:
            result = (u'''\\task{\n%s\n}\n''' % text).replace('\\\\u', '\\u')
        except Exception:
            log.exception('Failed to get LaTeX on %r', self.Text)
            raise
        if self.Answer:
            try:
                result += (u'''\\answer{\n    %s\n}\n''' % self.Answer).replace('\\\\u', '\\u')
            except Exception:
                log.exception('Failed to get LaTeX on answer %r', self.Answer)
                raise
        result += u'% autogenerated\n'
        return result        

    def GetFilename(self):
        filename = '%s.tex' % self.Number
        log.debug('Got filename %r from %r', filename, self.Number)
        return filename


class TasksGenerator(object):
    def __call__(self):
        raise NotImplementedError()
