import os

class Task(object):
    def __init__(self, text, answer=None, book=None, number=None):
        self.Text = text
        self.Answer = answer
        self.Book = book
        self.Number = number

    def GetTex(self):
        text = '. \n'.join('    ' + line for line in self.Text.split('. '))
        text += '\n    % autogenerated'
        result = u'\\task{{\n{}\n}}'.format(text).replace('\\\\u', '\\u')
        return result

    def GetFilename(self):
        return os.path.join(self.Book, '%s.tex' % self.Number)


class TasksGenerator(object):
    def __call__(self):
        raise NotImplementedError()
